language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN=96f32a2b-e640-44a1-88b8-6d2a551772ba

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always